language: go

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

go:
  - 1.10.x
  - master

install:
  - make get-deps

script:
  - go test ./
  - go test ./protocol
